services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:3000
    networks:
      rsm-challenge-network:

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      rsm-challenge-network:

volumes:
  pgdata:

networks:
  rsm-challenge-network:
